# Generated by Django 3.2 on 2022-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=30)),
                ('grandeza', models.CharField(max_length=30)),
                ('chave_a', models.CharField(max_length=30, unique=True)),
                ('chave_b', models.CharField(max_length=30)),
                ('chave_c', models.CharField(max_length=30)),
                ('ultima_leitura', models.CharField(max_length=30)),
                ('leitura_anterior', models.CharField(max_length=30)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='diferenca')),
                ('perc_diferenca', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='perc_diferenca')),
                ('situacao', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='situacao')),
            ],
        ),
    ]
