# Generated by Django 3.2 on 2022-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='chave_a',
            field=models.CharField(max_length=30),
        ),
    ]
